# Generated by Django 3.2.4 on 2021-06-07 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0002_auto_20210607_1445'),
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services_app.customer')),
                ('extra_tasks', models.ManyToManyField(blank=True, to='order_app.ExtraTask')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services_app.location', verbose_name='location Offer')),
            ],
        ),
    ]
